### ISSUE TITLE
requirements.txt 有误？

### ISSUE THREAD

**Issue by sadk** [nanshihui/toolforspider#4]
好像找不到 zenmap==7.12

**Comment by nanshihui** [comment]
zenmap 需要你自己先安装nmap。 我有写在wiki 上面。

**Comment by sadk** [comment]
nmap 我已经装了。但是pip好像找不到 zenmap这个包？（https://pypi.python.org/pypi/pip 这里也没有）

**Comment by sadk** [comment]
requirements里缺 MySQL-python

**Comment by nanshihui** [comment]
安装好了 nmap 以及 zmap 那你可以 不用管这个了，删掉就行了，因为requirement 是用工具生成的，所以他会把一些无关的东西，带进去。 另外 谢谢你的细心检查

**Comment by sadk** [comment]
我会写个安装过程的文档，然后出一个docker版。

**Comment by nanshihui** [comment]
谢了， 开源需要大家 一起努力，如果可以 麻烦你 push 上来

**Comment by sadk** [comment]
没问题 👍
